app:
  queue2-name: queue2.fifo

spring:
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566
        region: us-east-1
        listener:
          max-concurrent-messages: 1
          max-messages-per-poll: 1
      sns:
        endpoint: http://localhost:4566
        region: us-east-1
